name: deploy vue
on:
  push:
    branches: 
        - main
jobs:
    deploy-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code to build server
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: pnpm
            - name: build the code
              run: |
                pnpm install --no-frozen-lockfile
                pnpm build
            - name: copy file to sever
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.HOST}}
                username: ${{ secrets.SSH_USER_NAME}}
                key: ${{ secrets.SSH_KEY}}
                port: ${{ secrets.SSH_PORT}}
                source: "./dist/*"
                target: "/var/www/html"
                strip_components: 1
